<a href="https://colab.research.google.com/github/Toulou-png/Data-manipulation/blob/main/data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="" alt="image" width="200"/>

# Manipulation de données avec Pandas

In [5]:
import pandas as pd

## Chargement des Données
[lien vers les données](https://www.data.gouv.fr/fr/datasets/le-baccalaureat-par-academie/)

In [3]:
data = pd.read_csv("/content/fr-en-baccalaureat-par-academie.csv", sep=";")

In [ ]:
data

In [ ]:
data.columns.tolist()

In [ ]:
missing_values = data.isnull().sum()
missing_values

# Unique()
## Répondre à la question : Quels sont les éléments uniques d'une colonne ?
- e.g : quelles sont les différentes sessions d'examen dans notre cas ?

In [ ]:
data['Session'].unique().tolist()

In [ ]:
data['Code académie'].unique().tolist()

In [ ]:
data['Académie'].unique().tolist()

In [ ]:
data['Sexe'].unique().tolist()

In [ ]:
data['Statut du candidat'].unique().tolist()

In [ ]:
data['Voie'].unique().tolist()

In [ ]:
data['Série'].unique().tolist()

In [ ]:
data['Diplôme spécialité'].unique().tolist()

# value_counts()
## Répondre à la question : combien de fois chaque valeur unique apparaît-elle dans une colonne ?

- e.g : quel est le nombre total d'élèves pour chaque session ?

In [65]:
mention_counts = data['Session'].value_counts()
mention_counts

Session
2023    8653
2022    8522
2021    8407
Name: count, dtype: int64

In [66]:
mention_counts = data['Statut du candidat'].value_counts()
mention_counts

Statut du candidat
SCOLAIRE                   13759
APPRENTISSAGE               5408
INDIVIDUEL                  3961
FORMATION CONTINUE          1268
ENSEIGNEMENT A DISTANCE     1186
Name: count, dtype: int64

In [ ]:
mention_counts = data['Académie'].value_counts()
mention_counts

In [ ]:
mention_counts = data['Sexe'].value_counts()
mention_counts

## GroupBy

In [62]:
mention_par_annee = data.groupby(['Session', 'Sexe', 'Voie']).size().unstack()
mention_par_annee

Voie              BAC GENERAL  BAC PROFESSIONNEL  BAC TECHNOLOGIQUE
Session Sexe
2021    FEMININ            89               2847                714
        MASCULIN           89               3894                774
2022    FEMININ            90               2901                714
        MASCULIN           89               3993                735
2023    FEMININ            89               2987                718
        MASCULIN           90               4025                744

In [43]:
mention_par_annee = data.groupby(['Session', 'Académie']).size().unstack()
mention_par_annee

Académie,AIX-MARSEILLE,AMIENS,BESANCON,BORDEAUX,CLERMONT-FERRAND,CORSE,CRETEIL,DIJON,GRENOBLE,GUADELOUPE,...,NICE,NORMANDIE,ORLEANS-TOURS,PARIS,POITIERS,REIMS,RENNES,STRASBOURG,TOULOUSE,VERSAILLES
Session,,,,,,,,,,,,,,,,,,,,,
2021,344,275,244,368,276,116,317,295,338,172,...,271,361,337,262,285,269,331,279,359,340
2022,350,276,255,356,281,107,316,294,340,180,...,275,368,344,263,299,270,324,295,366,354
2023,364,282,262,370,284,114,337,283,341,188,...,262,382,347,265,304,264,319,293,371,351